question_data = [{"type": "boolean", "difficulty": "easy", "category": "Politics",
                  "question": "In 2016, the United Kingdom voted to stay in the EU.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
                  "question": "In Scandinavian languages, the letter &Aring; means river.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
                  "question": "Blue Danube was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                  "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "History",
                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Politics",
                  "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                  "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "A plant that has a life cycle for more than a year is known as an annual.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Tony Hawk&#039;s extreme sports videogames revolve around performing professional BMX tricks.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "An atom contains a nucleus.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Nintendo&#039;s Luigi was originally just called Green Mario?",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Celebrities",
                  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                  "question": "The book 1984 was published in 1949.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
                  "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                                                    "question": "Ferrari has never made a V10 engine for any of its cars.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "March 10th is also known as Mar10 Day.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "A cancelled Call Of Duty title would have taken place in ancient Rome.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "Upwelling in the ocean provides colder nutrient rich water for plants and decomposers.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "Ottoman Empire was created in 1299.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The majority of Subaru vehicles are made in China.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
                  "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
                  "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                  "question": "A pencil&#039;s lead is typically made from graphite, not lead",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                                   "question": "Hungary is the only country in the world beginning with H.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the Super Mario series, the character Pauline is a Princess like Princess Peach.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Animals",
                                                   "question": "Finnish Lapphund dogs were used for herding reindeer.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In the game &quot;Subnautica&quot;, a &quot;Cave Crawler&quot; will attack you.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
